
-- Jadvallarni o'chirish
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS UserSessions CASCADE;
DROP TABLE IF EXISTS Courier CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS courier_locations CASCADE;
DROP TABLE IF EXISTS Couriers CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS CourierOrders CASCADE;
DROP TABLE IF EXISTS schema_migrations;


-- Enum turlarini o'chirish
DROP TYPE IF EXISTS courier_status CASCADE;
DROP TYPE IF EXISTS User_role CASCADE;
DROP TYPE IF EXISTS OrderStatus CASCADE;
DROP TYPE IF EXISTS pay_status CASCADE;
DROP TYPE IF EXISTS CourOrd_status CASCADE;

-- UPDATE schema_migrations
-- SET dirty = false
-- WHERE version = 1;
-- UPDATE 1

